export { handler as copyHandler } from './copy'
export { handler as generalHandler } from './general'
export { handler as languagesHandler } from './languages'
export { handler as llmsHandler } from './llms'
export { handler as micHandler } from './mic'
export { getSelectedModel, handler as modelsHandler } from './models'
export { handler as onboardingHandler } from './onboarding'
export { handler as pasteHandler } from './paste'
export { handler as recordingsHandler } from './recordings'
export { handler as shortcutsHandler } from './shortcuts'
export { handler as speechToTextHandler } from './speech-to-text'
export { handler as updaterHandler } from './updater'
