/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>

export interface Recordings {
  audioFilePath: string
  createdAt: Generated<string>
  duration: number
  enhancedText: string | null
  id: string
  llmId: string | null
  modelId: string
  shortcutVersionId: string
  transcribedText: string | null
  updatedAt: Generated<string>
}

export interface Shortcuts {
  createdAt: Generated<string>
  currentVersion: number
  id: string
  status: Generated<string>
  updatedAt: Generated<string>
}

export interface ShortcutVersions {
  createdAt: Generated<string>
  id: string
  name: string
  prompt: string | null
  shortcut: string
  shortcutId: string
  version: number
}

export interface DB {
  recordings: Recordings
  shortcut_versions: ShortcutVersions
  shortcuts: Shortcuts
}
