name: CI Checks

on:
  workflow_call:

jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build (CI)
        run: yarn build:ci
